/**
 * Virtual Module Generator
 *
 * Produces the JavaScript source code for the Vite virtual module
 * `virtual:@stackra/ts-config`. The generated code exports the
 * configuration object and helper functions for accessing values.
 *
 * @module utils/generate-virtual-module
 */

/**
 * Generate the virtual module source code from a configuration object.
 *
 * Serializes the provided config into a self-contained JavaScript module
 * that can be resolved by Vite's virtual module system. The generated
 * module exports `config`, `get`, and `has` functions, and also sets
 * `window[globalName]` for `EnvDriver` backward compatibility.
 *
 * @param config - The merged configuration object (env + scanned files)
 * @param globalName - The window global variable name
 *   (default: `'__APP_CONFIG__'`)
 * @returns JavaScript source code as a string, ready to be served by Vite
 *
 * @example
 * ```typescript
 * const code = generateVirtualModule({ APP_NAME: 'MyApp' });
 * // Returns a string that Vite resolves as 'virtual:@stackra/ts-config'
 * ```
 */
export function generateVirtualModule(
  config: Record<string, any>,
  globalName: string = '__APP_CONFIG__'
): string {
  const configJson = JSON.stringify(config, null, 2);

  return `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by @stackra/ts-config Vite plugin.
 * Import this module to access configuration values at runtime.
 */

/**
 * The full configuration object.
 * Contains merged environment variables and scanned config file values.
 */
export const config = ${configJson};

/**
 * Get a configuration value by key.
 *
 * @param {string} key - Configuration key (supports dot notation)
 * @param {*} defaultValue - Fallback value if key is not found
 * @returns The configuration value, or defaultValue
 */
export function get(key, defaultValue) {
  const keys = key.split('.');
  let current = config;
  for (const k of keys) {
    if (current === null || current === undefined) return defaultValue;
    current = current[k];
  }
  return current !== undefined ? current : defaultValue;
}

/**
 * Check if a configuration key exists.
 *
 * @param {string} key - Configuration key (supports dot notation)
 * @returns {boolean} true if the key exists
 */
export function has(key) {
  const keys = key.split('.');
  let current = config;
  for (const k of keys) {
    if (current === null || current === undefined || !(k in current)) return false;
    current = current[k];
  }
  return true;
}

// Set window global for EnvDriver backward compatibility
if (typeof window !== 'undefined') {
  window.${globalName} = config;
}
`;
}
